MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    EXTERNAL_PROPOSAL: False
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 27
    NAME_OLD_CLASSES: []
    NAME_NEW_CLASSES: ['ALOMY', 'ANGAR', 'APESV', 'ARTVU', 'AVEFA',
                       'BROST', 'BRSNN', 'CAPBP', 'CENCY', 'CHEAL', 'CHYSE', 'CIRAR',
                       'CONAR', 'EPHHE', 'EPHPE', 'EROCI', 'FUMOF', 'GALAP', 'GERMO',
                       'LAPCO', 'LOLMU', 'LYCAR', 'MATCH', 'MATIN', 'MELNO', 'MYOAR',
                       ]
    NAME_EXCLUDED_CLASSES: ['PAPRH', 'PLALA', 'PLAMA', 'POAAN', 'POLAV', 'POLCO', 'POLLA',
                       'POLPE', 'RUMCR', 'SENVU', 'SINAR', 'SOLNI', 'SONAS', 'SONOL',
                       'STEME', 'THLAR', 'URTUR', 'VERAR', 'VERPE', 'VICHI', 'VIOAR']
  MASK_ON: False
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
    POSTPROCESS_MASKS: True
DATASETS:
  TRAIN: ("OPPD_train","OPPD_val")
  TEST: ("OPPD_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.005 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (48000,49000)
  MAX_ITER: 50000 # number of iteration
  CHECKPOINT_PERIOD: 10000 # number of iteration to generate check point
  IMS_PER_BATCH: 4 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "output/26-20/LR005_BS4_50K" # path to store the result
INCREMENTAL: False
#DTYPE: "float16"